# Generated by Django 4.1.3 on 2022-11-11 18:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("notes", "0003_rename_notes_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="importance",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                null=True,
                related_name="important",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
