# Generated by Django 4.1.3 on 2022-11-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0004_note_importance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="importance",
        ),
        migrations.AddField(
            model_name="note",
            name="status_code",
            field=models.CharField(
                choices=[("draft", "Draft"), ("saved", "Saved")],
                default="draft",
                max_length=15,
            ),
        ),
    ]
