# Generated by Django 4.1.3 on 2022-11-11 19:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("notes", "0005_remove_note_importance_note_status_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="importance",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                null=True,
                related_name="important",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="status_code",
            field=models.CharField(
                choices=[("saved", "Saved"), ("draft", "Draft")],
                default="draft",
                max_length=15,
            ),
        ),
    ]
