# Generated by Django 4.1.3 on 2022-11-12 03:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("notes", "0007_rename_importance_note_important_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="important",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                related_name="important",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
