# Generated by Django 4.1.3 on 2022-11-12 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0016_alter_note_status_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="status_code",
            field=models.CharField(
                choices=[("published", "Published"), ("draft", "Draft")],
                default="published",
                max_length=15,
            ),
        ),
    ]
