# Generated by Django 4.1.3 on 2022-11-13 16:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0018_alter_note_status_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="status_code",
        ),
        migrations.AddField(
            model_name="note",
            name="draft",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="note",
            name="saved",
            field=models.DateField(
                default=datetime.datetime(
                    2022, 11, 13, 16, 5, 18, 175091, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
    ]
