# Generated by Django 4.1.3 on 2022-11-14 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0020_alter_note_important"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="important",
        ),
        migrations.AddField(
            model_name="note",
            name="important",
            field=models.BooleanField(default=False),
        ),
    ]
